version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map Vite's default port to the host machine
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
